config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  resources :posts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title,{presence: true,length:{maximum:20}}
  validates :memo,length:{maximum:500}
  validates :start,presence: true
  validates :finish, presence: true
  validate  :start_end_check


  def start_end_check
    return false if start.blank? || finish.blank?
    if self.finish <= self.start
      errors.add(:error, "終了日は、開始日以降の日付としてください。")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:success] = "投稿しました"
      redirect_to("/")
    else
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:success] = "編集しました"
      redirect_to("/")
    else
      render 'edit'
    end
  end

  def destroy
    Post.find(params[:id]).destroy
    flash[:success] = "削除しました"
    redirect_to("/")
  end

  private
    def post_params
     params.require(:post).permit(:title, :start,:finish,:alltime,:memo )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/layouts/_header.html.erb
   <header>
      <div class="text-center " >
        スケジュール管理アプリ
      </div>
    </header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container-fluid ">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    　<%= yield %>
    </div>
    <script src="boostrap.bundle.min.js"></script>
  </body>
</html>

app/views/posts/edit.html.erb
<% provide(:title, "編集") %>
<div class="post_content">
  <h3>編集</h3>
  <%= render 'shared/error_messages' %>
  <%= form_with(model: @post, local: true) do |f| %>
    <%= f.label :title,"タイトル" ,class: "form-label" %>
    <%= f.text_field :title ,class: "form-control",value: @post.title %>
      <div class="row my-2">
        <div class="col-6">
          <%= f.label :start,"開始日",class: "form-label " %>
          <%= f.date_field  :start, class: " form-control "%>
        </div>
        <div class="col-6">
          <%= f.label :finish,"終了日",class: "form-label" %>
          <%= f.date_field :finish, class: "form-control"%>
        </div>
      </div>
      <div class="my-2">
        <%= f.check_box :alltime  %>
        <%= f.label :alltime,"終日の場合はチェックを入れてください" ,class: "form-label"%>
      </div>
    <%= f.label :memo,"スケジュールメモ",class: "form-label"%>
    <%= f.text_area :memo,class: "form-control" %>
    <div class="text-right">
       <%= link_to "キャンセル",  posts_path ,class: "btn btn-light" %>
       <%= f.submit "保存", class: "btn btn-primary my-2" %>
     </div>
  <% end %>
</div>

app/views/posts/index.html.erb
<% provide(:title, "投稿一覧") %>
<div class="pagetitle d-flex  justify-content-between">
 <h3>予定一覧</h3>
  <%= link_to "新規追加",  new_post_path ,class: "btn btn-primary" %>
</div>
<table class="table">
  <thead>
    <tr>
      <td> ID</td>
      <td> タイトル</td>
      <td> 開始日</td>
      <td> 終了日</td>
      <td> 終日</td>
      <td> 更新日時</td>
      <td colspan ="3"></td>
    </tr>
  </thead>
  <% @posts.each do |post| %>
    <tr>
      <td> <%= post.id %>　</td>
      <td> <%=post.title %> </td>
      <td> <%=post.start.strftime("%Y/%m/%d") %> </td>
      <td> <%=post.finish.strftime("%Y/%m/%d") %> </td>
      <td> <% if post.alltime == 1 %> <%= "○" %> <% end %> </td>
      <td> <%=post.updated_at.strftime("%Y/%m/%d %R") %> </td>
      <td> <%=link_to("詳細","/posts/#{post.id}") %> </td>
      <td> <%=link_to("編集","/posts/#{post.id}/edit") %> </td>
      <td> <%=link_to("削除","/posts/#{post.id}",method: :delete,data: { confirm: "本当に削除しますか？"}) %> </td>
    </tr>
  <% end %>
</table>
<footer  class="d-flex justify-content-between bg-light ">
  <p>予定合計 <%=@posts.count%>件</p>
  <p class="small">本日の日付 <%=Date.today.strftime("%Y/%m/%d") %></p>
</footer>

app/views/posts/new.html.erb
<% provide(:title, "新規投稿") %>
<div class="post_content">
  <h3>予定の新規追加</h3>
  <%= render 'shared/error_messages' %>
  <%= form_with(model: @post, local: true) do |f| %>

    <%= f.label :title,"タイトル" ,class: "form-label" %>
    <%= f.text_field :title ,class: "form-control" %>

    <div class="row my-2">
      <div class="col-6">
        <%= f.label :start,"開始日",class: "form-label " %>
        <%= f.date_field  :start, class: " form-control "%>
      </div>
      <div class="col-6">
        <%= f.label :finish,"終了日",class: "form-label" %>
        <%= f.date_field :finish, class: "form-control"%>
      </div>
    </div>
    <div class="my-2">
      <%= f.check_box :alltime  %>
      <%= f.label :alltime,"終日の場合はチェックを入れてください" ,class: "form-label"%>
    </div>
    <%= f.label :memo,"スケジュールメモ",class: "form-label"%>
    <%= f.text_area :memo,class: "form-control" %>
    <div class="text-right">
      <%= link_to "キャンセル",  posts_path ,class: "btn btn-light" %>
      <%= f.submit "保存", class: "btn btn-primary my-2" %>
    </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="post_content">
  <div class="d-flex  justify-content-between">
    <%=link_to "編集","/posts/#{@post.id}/edit",class: "btn btn-primary" %>
    <%=link_to("一覧に戻る","/") %>
  </div>
  <table class="table">
    <tr>
      <th class="table-light">タイトル</th>
    </tr>
    <tr>
      <td><%=@post.title%></td>
    </tr>
    <tr>
      <th class="table-light">開始日</th>
    </tr>
    <tr>
      <td><%=@post.start.strftime("%Y/%m/%d") %></td>
    </tr>
    <tr>
      <th class="table-light">終了日</th>
    </tr>
    <tr>
      <td><%=@post.finish.strftime("%Y/%m/%d") %></td>
    </tr>
    <tr>
      <th class="table-light">終日</th>
    </tr>
    <tr>
      <td><% if @post.alltime == 1 %> <%= "○" %> <% end %></td>
    </tr>
    <tr>
      <th class="table-light">スケジュールメモ</th>
    </tr>
    <tr>
      <td><%=@post.memo %></td>
    </tr>
  </table>
</div>

app/views/shared/_error_messages.html.erb
<% if @post.errors.any? %>
  <div id="error_explanation" 　>
    <ul class="alert alert-danger">
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>